### ISSUE TITLE
Change hardcoded path to dynamic path in TruncateTableGUI.au3

### ISSUE THREAD

**Issue by tobiasjakobs** [roedl-dynamics/TruncateDatabaseCruft#1]
Could you please check if it is possible to change the hardcoded path to dynamic path wit some thing like:

` %USERPROFILE%\Desktop`

https://github.com/roedl-dynamics/TruncateDatabaseCruft/blob/7232bdac266803adbd2523600c9944198d91bd7e/Scripts/TruncateTableGUI.au3#L24

**Comment by HenrykOhls** [comment]
Changed path to be dynamic, misunderstood FileInstall.
