### ISSUE TITLE
No compiled files in the Repository

### ISSUE THREAD

**Issue by tobiasjakobs** [roedl-dynamics/TruncateDatabaseCruft#4]
There should be no compiled or generated files in the repository. Please create a Releases to provide the EXE:
![grafik](https://user-images.githubusercontent.com/99735681/154239694-5b22b927-58c1-48af-bab9-78442728dabe.png)

**Comment by HenrykOhls** [comment]
Published [Release01](https://github.com/roedl-dynamics/TruncateDatabaseCruft/releases/tag/0.1).
